// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDezafrdDM09EDBB6rqDI-g1JXkDGJGl50',
    appId: '1:977991601300:web:371e15e847583caec3b881',
    messagingSenderId: '977991601300',
    projectId: 'scheduling-app-ecb21',
    authDomain: 'scheduling-app-ecb21.firebaseapp.com',
    storageBucket: 'scheduling-app-ecb21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJz1O4bu2Glo3BVey4_7RnNzcs88zPRX4',
    appId: '1:977991601300:android:cb9fa64b20171e6ec3b881',
    messagingSenderId: '977991601300',
    projectId: 'scheduling-app-ecb21',
    storageBucket: 'scheduling-app-ecb21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LJUAiTROYk9dt-kWqFQ7efVs0as8_dU',
    appId: '1:977991601300:ios:de9a593d84fb214bc3b881',
    messagingSenderId: '977991601300',
    projectId: 'scheduling-app-ecb21',
    storageBucket: 'scheduling-app-ecb21.appspot.com',
    androidClientId: '977991601300-4jibieev65g1c7kv6gjiktm5pavh8aei.apps.googleusercontent.com',
    iosClientId: '977991601300-ub76cruf18ekhn8n6m0fmbjf4r77ft0h.apps.googleusercontent.com',
    iosBundleId: 'com.ecs198f.schedulerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LJUAiTROYk9dt-kWqFQ7efVs0as8_dU',
    appId: '1:977991601300:ios:de9a593d84fb214bc3b881',
    messagingSenderId: '977991601300',
    projectId: 'scheduling-app-ecb21',
    storageBucket: 'scheduling-app-ecb21.appspot.com',
    androidClientId: '977991601300-4jibieev65g1c7kv6gjiktm5pavh8aei.apps.googleusercontent.com',
    iosClientId: '977991601300-ub76cruf18ekhn8n6m0fmbjf4r77ft0h.apps.googleusercontent.com',
    iosBundleId: 'com.ecs198f.schedulerApp',
  );
}
